"""Fernet wrapper for encrypting branch credentials at rest.

The key is read once from settings.fernet_key (44-char base64 from `.env`,
generated by scripts/init.sh). The same key must be used for the lifetime of
the database — rotating it requires re-encrypting every existing credential.
"""
from functools import lru_cache

from cryptography.fernet import Fernet, InvalidToken

from app.config import settings


@lru_cache(maxsize=1)
def _fernet() -> Fernet:
    key = settings.fernet_key.encode() if isinstance(settings.fernet_key, str) else settings.fernet_key
    return Fernet(key)


def encrypt(value: str | None) -> str | None:
    if value is None or value == "":
        return None
    return _fernet().encrypt(value.encode("utf-8")).decode("utf-8")


def decrypt(value: str | None) -> str | None:
    if value is None or value == "":
        return None
    try:
        return _fernet().decrypt(value.encode("utf-8")).decode("utf-8")
    except InvalidToken:
        # Wrong key or tampered ciphertext. Caller should treat as missing.
        return None
